workflows:
  android-build:
    name: Android Debug Build
    environment:
      vars:
        REACT_NATIVE_VERSION: "0.72.17"
        NODE_VERSION: "18.20.4"
        NPM_CONFIG_LEGACY_PEER_DEPS: "true"
    scripts:
      - name: Set up Node.js
        script: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          npm config set legacy-peer-deps true
      - name: Clean up and Install dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          rm -f yarn.lock
          rm -rf android/app/build
          rm -rf android/build
          rm -rf android/.gradle
          rm -rf .gradle
          rm -f android/app/src/main/assets/index.android.bundle
          npm cache clean --force
          npm cache verify
          npm install --legacy-peer-deps --exact
      - name: Bundle JS for Android
        script: |
          mkdir -p android/app/src/main/assets
          echo "Creating bundle with entry file: index.js"
          echo "App name from app.json: $(cat app.json | grep -o '"name": "[^"]*"' | cut -d'"' -f4)"
          echo "Current directory: $(pwd)"

          # Verify entry file exists
          if [ ! -f index.js ]; then
            echo "ERROR: index.js not found!"
            ls -la
            exit 1
          fi

          # Verify App.tsx exists
          if [ ! -f App.tsx ]; then
            echo "ERROR: App.tsx not found!"
            ls -la
            exit 1
          fi

          echo "Entry files exist, creating bundle..."

          # Create bundle with explicit configuration
          NODE_OPTIONS="--max-old-space-size=4096" npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res \
            --reset-cache \
            --verbose

          # Verify bundle was created
          if [ -f android/app/src/main/assets/index.android.bundle ]; then
            echo "✅ Bundle created successfully"
            echo "Bundle size: $(stat -f%z android/app/src/main/assets/index.android.bundle 2>/dev/null || echo 'unknown')"
            ls -la android/app/src/main/assets/
          else
            echo "❌ ERROR: Bundle creation failed!"
            echo "Checking for any generated files..."
            find android/app/src/main/assets/ -name "*.bundle" 2>/dev/null || echo "No bundle files found"
            exit 1
          fi
      - name: Build Android Debug
        script: |
          cd android
          chmod +x ./gradlew
          chmod +x ../node_modules/react-native/sdks/hermesc/osx-bin/hermesc || true
          ./gradlew --refresh-dependencies
          ./gradlew assemblePlayDebug
    artifacts:
      - android/app/build/outputs/apk/play/debug/*.apk
