workflows:
  android-build:
    name: Android Build
    environment:
      groups:
        - android-signing-key-release
      vars:
        REACT_NATIVE_VERSION: 0.72.17
        NODE_VERSION: 18.20.4
        NPM_CONFIG_LEGACY_PEER_DEPS: true
    scripts:
      - name: Set up Node.js
        script: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          npm config set legacy-peer-deps true
      - name: Clean up and Install dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          rm -rf android/app/build
          rm -rf android/build
          rm -rf android/.gradle
          rm -rf .gradle
          rm -f android/app/src/main/assets/index.android.bundle
          npm cache clean --force
          npm cache verify
          npm install --legacy-peer-deps
      - name: Bundle JS for Android
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: Build Android Release
        script: |
          cd android
          chmod +x ./gradlew
          chmod +x ../node_modules/react-native/sdks/hermesc/osx-bin/hermesc || true
          ./gradlew --refresh-dependencies
          ./gradlew assemblePlayRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
