workflows:
  android-build:
    name: Android Build
    environment:
      groups:
        - android-signing-key-release
      vars:
        REACT_NATIVE_VERSION: 0.72.17
    scripts:
      - name: Clean up and Install dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
      - name: Build Android Release
        script: |
          cd android
          chmod +x ./gradlew
          chmod +x ../node_modules/react-native/sdks/hermesc/osx-bin/hermesc
          ./gradlew --refresh-dependencies
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
