workflows:
  android-build:
    name: Android Build
    environment:
      groups:
        - android-signing-key-release
      vars:
        REACT_NATIVE_VERSION: 0.72.17
        NODE_VERSION: 18.20.4
    scripts:
      - name: Set up Node.js
        script: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
      - name: Clean up and Install dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          rm -rf android/app/build
          rm -rf android/build
          rm -rf android/.gradle
          rm -rf .gradle
          rm -f android/app/src/main/assets/index.android.bundle
          npm cache clean --force
          npm install
      - name: Install Expo CLI and fix dependencies
        script: |
          npm install -g @expo/cli
          echo "Expo CLI version: $(expo --version)"
          # Fix any Expo dependency issues
          npx expo install --fix
      - name: Create Expo configuration
        script: |
          # Ensure Expo can find the app configuration
          echo "Checking Expo configuration..."
          npx expo config --type public
      - name: Bundle JS for Android
        script: |
          mkdir -p android/app/src/main/assets
          # Use Expo's bundler if available, fallback to React Native
          if command -v expo &> /dev/null; then
            echo "Using Expo bundler..."
            npx expo export --platform android --output-dir android/app/src/main/assets
          else
            echo "Using React Native bundler..."
            npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          fi
      - name: Build Android Release
        script: |
          cd android
          chmod +x ./gradlew
          chmod +x ../node_modules/react-native/sdks/hermesc/osx-bin/hermesc || true
          ./gradlew --refresh-dependencies
          ./gradlew assemblePlayRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
